filter {
    # if ([field] == 4) and (([s] in ["string", "hi"]) or [f2] - 25 == 12){
    #     statedump {}
    # }
    # grok {
    #     match => {
    #         "source" => [
    #             "^grok_pattern$",
    #             "^grok_pattern$"
    #         ]
    #         "source1" => "grokpattern"
    #     }
    #     overwrite => [ "source" ]
    #     on_error => "zerror.grok_source"
    # }
    # json {
    #     source => "field"
    #     array_function => "split_columns"
    #     target => "field"
    #     on_error => "zerror.not_json_field"
    # }
    # xml {
    #     source => "field"
    #     xpath => {
    #         "source_path" => destination
    #     }
    #     on_error => "zerror.xml_field"
    # }
    # kv {
    #     source => "source"
    #     field_split => "field_split"
    #     value_split => "value_split"
    #     target => "target"
    #     on_error => "zerror.kv_source"
    # }
    # csv {
    #     source => "source"
    #     separator => "separator"
    #     target => "target"
    #     on_error => "zerror.csv_${source:source}"
    # }
    # base64 {
    #     source => "source"
    #     target => "target"
    #     encoding => "Standard"
    # }
    # date {
    #     match => [ 
    #         "source",
    #         "UNIX"
    #         "UNIX_MS"
    #         "ISO8601"
    #         "RFC3399"
    #         "yyyy-MM-dd HH:mm:ss",
    #         "yyyy-MM-d HH:mm:ss",
    #         "yyyy-M-dd HH:mm:ss",
    #         "yyyy-M-d HH:mm:ss"
    #     ]
    #     on_error => "zerror.date_source"
    # }
    # drop {
    #     tag => "%{1:drop_tag}"
    # }
    # statedump {}
    mutate {
        replace => {
            field_e => ""
        }
        on_error => "zerror.err_name"
    }
}